---
title: "First_Quarto_File"
editor: visual
execute:
  keep-md: true
warnings: false
format:
  html:
    code-fold: true
    code-line-numbers: true
---

```         
What is unique or good about the visualization? List a few ideas.
What could be better? Identify at least one issue with the visualization.
```

https://ourworldindata.org/half-child-deaths-linked-malnutrition

One positive thing about this visualization is that it can be viewed in a snapshot form, one year at a time, or the changes over time for each cause of child deathes. Antoher good thing is that the visuals utilize length, angle/slope, and color hue to communicate the data. There is also a table available, and I liked the ability to hover over a point to find additional details. However, ink could be reduced by creating a key to explain the different causes rather than including text on the chart.

https://ourworldindata.org/antibiotics-livestock

One positive thing about this visual is that the color hue is used for a color code, and they are distinct enough to recognize the difference, even if looking at two points far apart from each other. Additionally, length is used for visualization, and the data is organized by number rather than alphabetically. This makes it easy to understand the story. When hovering over the lines, they reveal more details about the country, and when hovering over the key, specific regions are highlighted for better visual discernment. However, the lines are very small and it is difficult to hover over one specific line without bumping into another.Additionally, a few different coutnries have been labeled at the bottom and I am unsure why they are more important than others, especially since it is not arranged alphabetically or by region.

https://ourworldindata.org/part-two-how-many-people-die-from-extreme-temperatures-and-how-could-this-change-in-the-future

One positive aspect of the first visual is that it is organized by percentage, rather than alphabetically. Additionally, two distinct colors are used to indicate two different variables and they are very easy to differentiate. Length is also utilized in this visual to express amounts and it is easy to compare the overall differences of the countries. However, there is ink in the visual that could be reduced by removing the percentages listed within the bars. Additionally, the bars are stacked on top of each other, which wouldd make it slightly more difficult to compare some of the data, which is likely why the percentages were included.

```{r}
plot(1:20)

```
