---
title: "Strings and Regex"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(stringi)

```

```{r}
randomletters <- read_lines("https://byuistats.github.io/M335/data/randomletters.txt")

randomletnums <- readr::read_lines("https://byuistats.github.io/M335/data/randomletters_wnumbers.txt")

```

## Hidden Quote

```{r}

letters_quote <- str_c(randomletters, collapse = "") %>% 
  str_split("", simplify = TRUE) %>% 
  .[1, ] %>% 
  .[seq(0, length(.), by = 1700)]

letters_quote

# the plural of anecdote is not data.'

letters_split <- str_split(randomletters, pattern = "")[[1]]
my_seq <- seq(from = 0, to = length(letters_split), by = 1700)

my_seq[1] <- 1

letters_split[my_seq]


```

## Secret Message

```{r}
numbers <- str_extract_all(randomletnums, "\\d+") %>% unlist() %>% as.numeric()

code <- letters[numbers]

code

# experts often possess more data than judgment

```

## Longest Sequence of Vowels

```{r}
vowels <- str_extract_all(randomletters, "[aeiou]{7,}")

vowels

# I ran the code using 3, then 4, then 5, etc.

# oaaoooo

```
