---
title: "Distance Between pt 2"
format: 
  html:
    code-fold: true
    code-line-numbers: true
editor: visual
execute: 
  keep-md: true
warnings: false
---

```{r}
library(tidyverse)
library(stringi)

scriptures <- read_csv("https://github.com/beandog/lds-scriptures/raw/master/csv/lds-scriptures.csv")

savior_names <- read_rds("https://byuistats.github.io/M335/data/BoM_SaviorNames.rds")
```

```{r}

the_names <- str_c(savior_names$name, collapse = "|")

books <- function(x) {
  scriptures2 <- str_c(x$scripture_text) %>% 
  str_flatten() %>% str_split(pattern = the_names)
  word_count <- unlist(scriptures2) %>% str_count(pattern = "\\S+") 
}

scriptures <- scriptures %>% 
  filter(volume_short_title == "BoM")

scriptures2 <- scriptures %>% 
  group_by(book_title) %>% 
  nest() %>% 
  mutate(distance_between = map(data, books)) %>% 
  select(c(book_title, distance_between)) %>% 
  unnest(distance_between)

  
```


```{r}

ggplot(scriptures2, aes(x = distance_between, fill = book_title, color = book_title)) +
  geom_area(stat = "bin") +
  labs(x = "Number of Words Between Instances of Savior Names",
       y = NULL, 
       title = "There is an average of 63.2 words between each instance of the Savior's name.") +
  scale_y_continuous(limits = c(0, 10),
                     labels = NULL, ) +
  scale_x_continuous(trans = "sqrt",
                     limits = c(0, 2000)) +
  theme_classic() +
  theme(axis.ticks.y = element_blank(),
        strip.text = element_blank(),
        legend.title = element_text()) +
  facet_grid(book_title~.)

# mean_count <- mean(word_count)
# # 63.2
# 
# word_tibble <- tibble(word_count) %>% 
#   filter(word_count >= 0)

```

```{r}

```
