---
title: "birth rates and death rates"
format: html
editor: visual
---

```{r}
df <- read_csv("https://ourworldindata.org/grapher/births-and-deaths.csv?v=1&csvType=full&useColumnShortNames=true")

library(ggrepel)


```


```{r}
View(df)

birth_death <- df %>% 
  filter(Code == "USA") %>% 
  rename("Death Rate" = death_rate__sex_total, 
         "Birth Rate" = cbr__birth_order_total) %>% 
  pivot_longer(cols = "Death Rate":"Birth Rate", values_to = "rate", names_to = "type")

mylines = tibble(x = 1933, xend = 2022, y = seq(5, 25, 5))

```


```{r}
ggplot(birth_death, aes(x = Year, y = rate, color = type)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(breaks = seq(0, 25, by = 5), 
                     limits = c(0, 26)) +
  scale_x_continuous(breaks = c(1933, seq(1940, 2000, 20), 2022), 
                     limits = c(1933, 2030),
                     expand = expansion(mult = c(0, 0.5))) +
  labs(title = "Birth and death rate, United States",
       subtitle = "Estimated number of annual births and deaths per 1,000",
       caption = "Data source: Human Mortality Database (2024); Human Fertility Database (2024) – Learn more about this data\n
OurWorldinData.org/population-growth | CC BY") +
  theme_minimal() +
  theme(panel.grid = element_blank(),
        axis.title = element_blank(),
        legend.position = "none",
        axis.ticks.x = element_line(),
        axis.ticks.length.x = unit(4, "points")) +
  scale_color_manual(values = c("#6c84ad", "#c97353")) +
  annotate(geom = "text", x = 2023, y = 10, label = "Death", hjust = 0, color = "#c97353", size = 3) +
  annotate(geom = "text", x = 2023, y = 11.5, label = "Birth", hjust = 0, color = "#6c84ad", size = 3) +
  geom_segment(data = mylines, aes(x = x, xend = xend, y = y, yend = y), color = "lightgray", lty = 2) +
  geom_segment(x = 1933, xend = 2022, y = 0, yend = 0, color = "gray", size = .75)
  

```
