---
title: "birth rates and death rates"
format: html
editor: visual
---

```{r}
df <- read_csv("https://ourworldindata.org/grapher/births-and-deaths.csv?v=1&csvType=full&useColumnShortNames=true")

library(ggrepel)


```


```{r}
View(df)

birth_death <- df %>% 
  filter(Code == "USA") %>% 
  rename("Death Rate" = death_rate__sex_total, 
         "Birth Rate" = cbr__birth_order_total) %>% 
  pivot_longer(cols = "Death Rate":"Birth Rate", values_to = "rate", names_to = "type")
```


```{r}
ggplot(birth_death, aes(x = Year, y = rate, color = type)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(breaks = seq(0, 25, by = 5), limits = c(0, 26)) +
  scale_x_continuous(breaks = c(1933, seq(1940, 2000, 20), 2022)) +
  labs(title = "Birth and death rate, United States",
       subtitle = "Estimated number of annual births and deaths per 1,000",
       caption = "Data source: Human Mortality Database (2024); Human Fertility Database (2024) – Learn more about this data\n
OurWorldinData.org/population-growth | CC BY") +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_line(linetype = 2),
        axis.title = element_blank(),
        legend.position = "none") +
  scale_color_manual(values = c("#6c84ad", "firebrick")) +
  geom_text_repel(aes(label = type))
  

```
