---
title: "Clean and Reformat"
author: "Annabelle Idell"
format: 
  html:
    code-fold: true
    code-line-numbers: true
editor: visual
execute: 
  keep-md: true
warnings: false
---

```{r}
library(tidyverse)
library(pander)
Darts <- readRDS("Dart_Expert_Dow_6month_anova.rds")
```

```{r}
darts2 <- Darts %>% 
  separate(contest_period, into = c("month_begin", "year_end")) %>% 
  separate(year_end, into = c("month_end", "year_end"), sep = -4, remove = FALSE) %>%
  mutate(month_end = ifelse(month_end == "", year_end, month_end)) %>%
  mutate(year_end = ifelse(month_end == year_end, "1993", year_end)) %>% 
  mutate(month_end = ifelse(month_end == "Dec", "December", month_end)) %>% 
  mutate(month_end = ifelse(month_end == "Febuary", "February", month_end))

```

```{r}


darts_table <- darts2 %>%
  filter(variable == "DJIA") %>%
  mutate(
    Month = factor(month_end, levels = month.name, ordered = TRUE)) %>% 
  select(c(Month, year_end, value)) %>% 
  pivot_wider(names_from = year_end, values_from = value) %>% 
  arrange(Month)

darts_table %>% pander()
```
